### ISSUE TITLE
Error using `SeededFileStore` cache

### ISSUE THREAD

**Issue by ahal** [mozilla/adr#82]
Running the seeded file store cache locally, I hit this error:
```
10:25:55.062 | INFO     | adr.util.cache_stores:63  - Seeding adr cache at /home/ahal/tmp/adr_cache with contents from https://s3-us-west-2.amazonaws.com/communitytc-bugbug/data/adr_cache.tar.zst
Traceback (most recent call last):
  File "/home/ahal/.cache/pypoetry/virtualenvs/ci-recipes-XbmlO8Rq-py3.7/bin/adr", line 10, in <module>
    sys.exit(main())
  File "/home/ahal/.cache/pypoetry/virtualenvs/ci-recipes-XbmlO8Rq-py3.7/lib64/python3.7/site-packages/adr/cli.py", line 237, in main
    result = handler(remainder)
  File "/home/ahal/.cache/pypoetry/virtualenvs/ci-recipes-XbmlO8Rq-py3.7/lib64/python3.7/site-packages/adr/cli.py", line 194, in handle_recipe
    data = run_recipe(config.recipe, remainder)
  File "/home/ahal/.cache/pypoetry/virtualenvs/ci-recipes-XbmlO8Rq-py3.7/lib64/python3.7/site-packages/adr/recipe.py", line 91, in run_recipe
    output = mod.run(Namespace(**parsed_args))
  File "/home/ahal/dev/ci-recipes/recipes/compare_pushes.py", line 102, in run
    push_manifests = get_manifests_by_task(push)
  File "/home/ahal/dev/ci-recipes/recipes/compare_pushes.py", line 51, in get_manifests_by_task
    tasks = [t for t in push.tasks
  File "/home/ahal/.cache/pypoetry/virtualenvs/ci-recipes-XbmlO8Rq-py3.7/lib64/python3.7/site-packages/adr/util/memoize.py", line 45, in __get__
    setattr(instance, name, self.func(instance))
  File "/home/ahal/.cache/pypoetry/virtualenvs/ci-recipes-XbmlO8Rq-py3.7/lib64/python3.7/site-packages/mozci/push.py", line 291, in tasks
    add(run_query("push_tasks_from_treeherder", args))
  File "/home/ahal/.cache/pypoetry/virtualenvs/ci-recipes-XbmlO8Rq-py3.7/lib64/python3.7/site-packages/adr/query.py", line 126, in run_query
    if config.cache.has(key):
  File "/home/ahal/.cache/pypoetry/virtualenvs/ci-recipes-XbmlO8Rq-py3.7/lib64/python3.7/site-packages/cachy/repository.py", line 33, in has
    return self.get(key) is not None
  File "/home/ahal/.cache/pypoetry/virtualenvs/ci-recipes-XbmlO8Rq-py3.7/lib64/python3.7/site-packages/cachy/repository.py", line 47, in get
    val = self._store.get(key)
  File "/home/ahal/.cache/pypoetry/virtualenvs/ci-recipes-XbmlO8Rq-py3.7/lib64/python3.7/site-packages/adr/util/cache_stores.py", line 91, in get
    self.seed()
  File "/home/ahal/.cache/pypoetry/virtualenvs/ci-recipes-XbmlO8Rq-py3.7/lib64/python3.7/site-packages/adr/util/cache_stores.py", line 75, in seed
    extract_tar_zst(fh.name, tempdir)
  File "/home/ahal/.cache/pypoetry/virtualenvs/ci-recipes-XbmlO8Rq-py3.7/lib64/python3.7/site-packages/adr/util/cache_stores.py", line 19, in extract_tar_zst
    tar.extractall(dest)
  File "/usr/lib64/python3.7/tarfile.py", line 2002, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib64/python3.7/tarfile.py", line 2044, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib64/python3.7/tarfile.py", line 2114, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib64/python3.7/tarfile.py", line 2163, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/usr/lib64/python3.7/tarfile.py", line 255, in copyfileobj
    raise exception("unexpected end of data")
tarfile.ReadError: unexpected end of data
```

I'm unsure if this is intermittent, a problem with the implementation in `adr` or some sort of corruption in the uploaded bugbug artifact. Though even in the latter case, we should handle it gracefully and not error out.

**Comment by ahal** [comment]
Here is my `config.toml`:
```
[adr]
verbose = 1

[adr.cache]
retention = 10080

[adr.cache.stores.file]
driver = "seeded-file"
path = "/home/ahal/tmp/adr_cache"
url = "https://s3-us-west-2.amazonaws.com/communitytc-bugbug/data/adr_cache.tar.zst"
archive_relpath = "data/adr_cache"
reseed_interval = 10080
```

**Comment by marco-c** [comment]
The extraction code is almost the same as the one in bugbug: https://github.com/mozilla/adr/blob/958cbfd837e81d834a9bee35c72b5ac66279e7b2/adr/util/cache_stores.py#L13-L19 vs https://github.com/mozilla/bugbug/blob/8f994b9db6b48114293aafd904c75285e523ec90/bugbug/utils.py#L253-L258.

The data collection task is running right now, I wonder if you weren't lucky and just downloaded the file while the task was uploading it.

**Comment by marco-c** [comment]
We are using a S3-based cache now, so this is no longer so important (and was probably an intermittent error anyway).
